### ISSUE TITLE
Parent account open/close error with autoclose_tree

### ISSUE THREAD

**Issue by scanta2** [redstreet/beancount_reds_plugins#19]
Here's an example of a project that shows an error in fava about the parent account getting closed before the opening date. I think the parent account does not get opened properly, or possibly it is assigned an opening date that is not earlier than the children's date.

```
option "operating_currency" "USD"
option "conversion_currency" "USD"

plugin "beancount.plugins.auto_accounts"
plugin "beancount_reds_plugins.autoclose_tree.autoclose_tree" 

2021-06-17 close Expenses:Non-Retirement:Auto:Fit

2019-01-01 * "Transaction"
  Expenses:Non-Retirement:Auto:Fit:Insurance      10 USD
  Expenses:Non-Retirement:Auto:Fit:Gas            20 USD
  Assets:Transfer
```

**Comment by redstreet** [comment]
Ah, `beancount.plugins.auto_accounts` inserts an `Open` for `Expenses:Non-Retirement:Auto:Fit` because it sees the close directive for it. The `Open` and `Close` occur on the same date, leading to this error.

The solution here might be to get `auto_accounts` to not add `open`s for `close` directives. Let me ask @blais for his thoughts.

**Comment by blais** [comment]
On vacation, so not getting the full context of this, only on my phone, but
closing an account without opening one will trigger an error. If the error
is that open and close happen on the same date maybe adjusting the
generation of open date makes more sense.

**Comment by redstreet** [comment]
@blais, please ignore this thread, it's been resolved. If you're curious, here's context: 

```
beancount.plugins.auto_accounts
2020-01-01 close Assets:Bank
```

looks like this after the `auto_accounts` plugin runs:

```
beancount.plugins.auto_accounts
2020-01-01 open Assets:Bank
2020-01-01 close Assets:Bank
```

This is well and fine normally, but the new `autoclose_tree` plugin I wrote overloads the close syntax to close children of parent accounts that were never opened. Except, when used in conjunction with `auto-accounts`, that parent account inadvertently gets opened (on the same date as the close).

I originally tagged you because a "clean" solution is to get `auto_accounts` to *not* generate `open`s for accounts which appear solely in a `close` directive. Instead, I decided to solve it by detecting this case in `autoclose_tree`.

**Comment by scanta2** [comment]
Thanks! Works well now
